apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  labels:
    app: app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
       app: app-v1
  template:
    metadata:
       labels:
          app: app-v1
    spec:
      containers:
      - name: sample-ctr
        image: saikiranreddy1808/deploy:v1
        ports:
        - containerPort: 80
        env:
        - name: CONF_USER
          valueFrom:
            configMapKeyRef:
               name: user-cred
               key: user
        - name: USER_PASS
          valueFrom:
            secretKeyRef:
               name: mysecret
               key: password  
