apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/images"
        backend:
          service:
            name: svc1
            port: 
              number: 80
      - pathType: Prefix
        path: "/posts"
        backend:
          service:
            name: svc1
            port: 
              number: 80

